AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mailing-list

  SAM Template for mailing-list

Globals:
  Function:
    Timeout: 3

Resources:
  ViewGroupsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: view_groups/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        MailingList:
          Type: Api
          Properties:
            Path: /groups
            Method: get
Outputs:
  ViewGroupsApi:
    Description: "API Gateway endpoint URL for Prod stage for ViewGroupsFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/groups/"
